//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;

    public partial class Zapatillas : IComparable<Zapatillas>
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Zapatillas()
        {
            this.Inventario = new HashSet<Inventario>();
        }

        public string SKU { get; set; }
        public string Marca { get; set; }
        public string Modelo { get; set; }
        public string Imagen { get; set; }
        public System.DateTime FechaLanzamiento { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public string Link { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Inventario> Inventario { get; set; }

        public int CompareTo(Zapatillas other)
        {
            if (other == null) return 1;

            int result = string.Compare(this.SKU, other.SKU, StringComparison.Ordinal);
            if (result != 0) return result;

            result = string.Compare(this.Nombre, other.Nombre, StringComparison.Ordinal);
            if (result != 0) return result;

            result = string.Compare(this.Marca, other.Marca, StringComparison.Ordinal);
            if (result != 0) return result;

            result = string.Compare(this.Modelo, other.Modelo, StringComparison.Ordinal);
            if (result != 0) return result;

            result = this.FechaLanzamiento.CompareTo(other.FechaLanzamiento);
            if (result != 0) return result;

            result = string.Compare(this.Descripcion, other.Descripcion, StringComparison.Ordinal);
            return result;
        }
    }

    public partial class ZapatillasDisplay
    {
        public string SKU { get; set; }
        public string Marca { get; set; }
        public string Modelo { get; set; }
        public System.DateTime FechaLanzamiento { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
    }

    public partial class ZapatillasAdd
    {
        public string SKU { get; set; }
        public decimal Precio { get; set; }
    }
}
